# Generated by Django 5.0.4 on 2024-05-06 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_system', '0002_leave_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_leaves', to='leave_system.profile'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='type',
            field=models.CharField(choices=[('Vacation', 'Vacation'), ('Sick', 'Sick')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='leave_system.leave')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='leave_system.profile')),
            ],
        ),
    ]
