# Generated by Django 5.0.4 on 2024-05-07 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_system', '0005_alter_request_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='leave_request',
        ),
        migrations.AddField(
            model_name='comment',
            name='leave',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='leave_system.leave'),
        ),
    ]
